image: python:3.8.6-alpine3.12

stages:
  - test
  - publish

cache:
  paths:
    - .pip
before_script:
  - python --version
  - export POETRY_VERSION=1.1.4
  - pip install "poetry==$POETRY_VERSION"
  - poetry install
#  - pip --cache-dir=.pip install -e . && pip install -e '.[dev]'

.base_tests:
  after_script:
    - echo Hi
#      - bash <(curl -s https://codecov.io/bash)

python36:
  extends: .base_tests
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  extends: .base_tests
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  extends: .base_tests
  image: python:3.8
  stage: test
  script: tox -e py38

publish:
  stage: publish
  image: 'python:3.8'
  script:
    - poetry publish --build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]*.[0-9]*.[0-9]*/'
      when: on_success